### ISSUE TITLE
[Feature]: Setting to specify parent property

### ISSUE THREAD

**Issue by oldjove** [JinMuGo/obsidian-go-up#3]
### **Overview**

Possibly a useful feature for this plugin would be the ability to specify which property corresponds with "up". E.g. some people might use "parent" or some other property name for the same purpose.

### **Describe the solution you'd like**

Introduce a setting to allow users to customize their "up" property.

**Comment by JinmuGo** [comment]
okay such a good idea!

**Comment by JinmuGo** [comment]
this feature added!

**Comment by oldjove** [comment]
Wonderful. Thank you!
