### ISSUE TITLE
Feature:  Go Up should automatically detect and convert a text to a link.

### ISSUE THREAD

**Issue by mariomui** [JinMuGo/obsidian-go-up#5]
### **Overview**

Linked Data Vocabularies can populate the "up" field with data. This data is not in the form of [[a-link]]. In stead it is simple text "A-link". Therefore the Go Up function does not activate and user does not go up.

* The current stop gap solution is to edit "broader: Authorship" into "broader: [[Authorship]]" 

### **Describe the solution you'd like**

As a user, I'd like to Go Up without having to revise the "up" field. It should remain text but still allow me to go up to a note with the same title. 

### *Possible Solution*

wrapping the text with getFirstLinkpathDest/getLInkPath should resolve this issue.

**Comment by JinmuGo** [comment]
okay i got it! 

If the 'parent' is the parent page, could we at least update the 'up' attribute to 'parent' to make it navigable?

**Comment by mariomui** [comment]
You mistook me. With the recent update, you allowed the user to update the default "parent" field to use a user-chosen field. My goal is for a text only link such as Authorship to be take the user to the note "Authorship"

**Comment by JinmuGo** [comment]
sorry for late answer!

if an Authorship note already exists, Do you want to move the "Author" text and [[Author]] (which is a link) to the parent note as well?
