### ISSUE TITLE
[Feature]: Integration with Folder Notes

### ISSUE THREAD

**Issue by agnoldo** [JinMuGo/obsidian-go-up#6]
First of all, thank you @JinMuGo for the implementation of the plugin. A great idea, very useful!

Do you know Folder Notes plugin? Your plugin (Go Up) is a perfect match for Folder Notes. Imagine if you just check if there is a folder note on the folder where the note is stored and automatically creates the link?

I implemented a Dataview JS script on every note, as the picture below shows:

![image](https://github.com/JinMuGo/obsidian-go-up/assets/4511589/cd5b4c75-ec7d-4f74-902a-0704b0a59c01)

But the result is not as good as yours, since every note in my vault has a long script at the beginning. I would love to use a plugin like yours, but without having to create a Frontmatter property.

**Comment by JinmuGo** [comment]
thank you for using my tiny plugins :) 

let me know which plugin you indicate with urls

1. https://github.com/xpgo/obsidian-folder-note-plugin
2. https://github.com/LostPaul/obsidian-folder-notes
3. or something.... 

And can you tell us in detail what behaviour you want?

**Comment by agnoldo** [comment]
Dear @JinMuGo , thanks for your (very) fast response! I forgot to mention that I use the AidenLx version:

https://github.com/aidenlx/alx-folder-note
https://github.com/aidenlx/folder-note-core
https://github.com/aidenlx/alx-folder-note-folderv

My idea was simply having a switch in Settings allowing me to enable the automatic insertion of a link to the folder note of the folder where the note is stored (if the folder note exists).

A plus would be defining a prefix and a suffix for the line, so I could insert an emoji such as ⤴️ before or after the link, to make it stand out on the note...

All the best!

**Comment by JinmuGo** [comment]
Okay i got it!
Hmmm I think it would be nice to automatically generate a markdown file with the name of that folder and link to it when the switch is turned on! I'll try to develop it that way, what do you think?

**Comment by agnoldo** [comment]
Hello, @JinMuGo . Thanks for your reply.

Please forgive me if I didn't understand your point but AidenLx's folder note plugins does exactly that. Here is an example:

![image](https://github.com/JinMuGo/obsidian-go-up/assets/4511589/c0f32c9c-cd13-4aa8-a771-d580f795c3af)

I created a folder note for this folder "2023_Essencia_da_Filosofia" by (1) installing and enabling the plugin; and (2) by Ctrl-Click on the folder. A new note for the folder was automatically created, with the name of the folder, stored inside the folder and following a template I defined on the plugin settings.

So, the only thing needed by "Obsidian Go Up" is to create a link on the top of the other note "Módulo 1 - Filosofia Antiga" pointing to "2023_Essencia_da_Filosofia".

Thanks again and greetings from Brazil!

**Comment by JinmuGo** [comment]
Oh! I checked the plugin and it creates a note with the same name and uses it as a folder note. That's why I made the suggestion above! Sorry for not providing context!

**Comment by agnoldo** [comment]
Thanks, @JinMuGo !

**Comment by agnoldo** [comment]
Thanks, @JinMuGo !

**Comment by JinmuGo** [comment]
No problem! let me know if you run into any problems while using it.

**Comment by agnoldo** [comment]
It worked perfectly with new notes. I replaced my old code:

`$=(dv.current().file.path.split("/").length > 2 || dv.current().document != "folder_note") ? dv.paragraph("[[" + dv.current().file.path.replaceAll(":", "\_").split("/").slice(0, -1 -(dv.current().document == "folder_note" ? 1 : 0)).join("/") + "/" + dv.current().file.path.split("/").slice(-2  -(dv.current().document == "folder_note" ? 1 : 0))[0] + "|⤴ " + dv.current().file.path.split("/").slice(-2 -(dv.current().document == "folder_note" ? 1 : 0))[0] + "]]") : dv.paragraph("[[_Principal|⤴ Principal]]")`

With the new one below thanks to your plugin:

⤴ `= this.up`
